language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['HEROKU_API_SECURE'] %>
  app: <%= ENV['HEROKU_APP_NAME'] %>
  on:
    repo: max-borisov/rails-simple-instagram
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:migrate
- bundle exec rake db:seed
script:
- bundle exec rspec spec/
